env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - 'plugin:@typescript-eslint/recommended'
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: ./tsconfig.json
  extraFileExtensions: [.vue]
plugins: ['vue', '@typescript-eslint']
rules: 
  '@typescript-eslint/array-type': [warn, {default: generic, readonly: generic}]
  '@typescript-eslint/comma-dangle': [warn, never]
  '@typescript-eslint/dot-notation': warn
  '@typescript-eslint/indent': [warn, 2, {SwitchCase: 1}]
  '@typescript-eslint/member-delimiter-style':
     - warn
     - multiline:
         delimiter: semi
         requireLast: true
       singleline:
         delimiter: comma
         requireLast: false
       multilineDetection: brackets
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-extra-parens': [warn, all]
  '@typescript-eslint/no-extra-semi': warn
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/prefer-readonly': warn
  '@typescript-eslint/quotes': [warn, single, {avoidEscape: true}]
  '@typescript-eslint/require-await': warn
  '@typescript-eslint/return-await': warn
  '@typescript-eslint/semi': [warn, always]
  arrow-body-style: [warn, as-needed]
  arrow-parens: [warn, as-needed]
  consistent-return: warn
  consistent-this: [warn, that]
  constructor-super: warn
  curly: [warn, all]
  default-case: warn
  dot-location: [warn, property]
  eol-last: warn
  eqeqeq: warn
  func-style: [warn, declaration]
  implicit-arrow-linebreak: [warn, beside]
  no-param-reassign: warn
  no-sequences: warn
  no-unneeded-ternary: warn
  no-var: warn
  object-curly-newline: [warn, {consistent: true}]
  object-shorthand: warn
  operator-assignment: [warn, always]
  prefer-const: warn
  prefer-numeric-literals: warn
  prefer-promise-reject-errors: warn
  prefer-rest-params: warn
  prefer-spread: warn
  quote-props: [warn, consistent-as-needed]
  require-yield: warn
  yoda: warn
  vue/html-self-closing:
    - warn
    - html:
        void: always
        normal: always
        component: always
      svg: always
      math: always
